import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ApiService, Book } from '../../core/api.service';

@Component({ standalone:true, imports:[ReactiveFormsModule], template:`
<div class="page-shell"><div class="d-flex flex-column flex-sm-row justify-content-between gap-3 mb-4"><div><h1 class="h2 mb-1">My Books</h1><p class="text-body-secondary mb-0">Keep your reading collection organized.</p></div><button class="btn btn-primary btn-mobile-full align-self-sm-start" (click)="startAdd()"><i class="fa-solid fa-plus me-2"></i>Add new book</button></div>
@if(error()){<div class="alert alert-danger">{{error()}}</div>}
@if(showForm()){<div class="card mb-4"><div class="card-body"><h2 class="h5">{{editingId() ? 'Edit book':'Add a new book'}}</h2><form [formGroup]="form" (ngSubmit)="save()"><div class="row g-3"><div class="col-md-5"><label class="form-label">Title</label><input class="form-control" formControlName="title"></div><div class="col-md-4"><label class="form-label">Author</label><input class="form-control" formControlName="author"></div><div class="col-md-3"><label class="form-label">Publication date</label><input type="date" class="form-control" formControlName="publishedDate"></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" [disabled]="form.invalid">Save</button><button type="button" class="btn btn-secondary" (click)="cancel()">Cancel</button></div></div></form></div></div>}
@if(!books().length){<div class="empty-state"><i class="fa-solid fa-book-open fa-3x text-primary mb-3"></i><h2 class="h4">No books yet</h2><p class="text-body-secondary">Add your first book to begin.</p></div>}@else{<div class="row g-3">@for(book of books();track book.id){<div class="col-12 col-md-6 col-lg-4"><article class="card h-100"><div class="card-body"><h2 class="h5">{{book.title}}</h2><p class="mb-1">{{book.author}}</p><p class="small text-body-secondary">{{book.publishedDate || 'Publication date unknown'}}</p><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" (click)="edit(book)"><i class="fa-solid fa-pen me-1"></i>Edit</button><button class="btn btn-sm btn-outline-danger" (click)="remove(book)"><i class="fa-solid fa-trash me-1"></i>Delete</button></div></div></article></div>}</div>}</div>`})
export class BooksComponent{
 private api=inject(ApiService);private fb=inject(FormBuilder);readonly books=signal<Book[]>([]);readonly showForm=signal(false);readonly editingId=signal<number|null>(null);readonly error=signal('');
 readonly form=this.fb.nonNullable.group({title:['',Validators.required],author:['',Validators.required],publishedDate:['']});constructor(){this.load();}
 load(){this.api.books.list().subscribe({next:x=>this.books.set(x),error:()=>this.error.set('Could not load books.')});} startAdd(){this.editingId.set(null);this.form.reset();this.showForm.set(true);} edit(b:Book){this.editingId.set(b.id);this.form.setValue({title:b.title,author:b.author,publishedDate:b.publishedDate??''});this.showForm.set(true);} cancel(){this.showForm.set(false);this.form.reset();}
 save(){if(this.form.invalid)return;const v=this.form.getRawValue();const data={...v,publishedDate:v.publishedDate||null};const req=this.editingId()?this.api.books.update(this.editingId()!,data):this.api.books.create(data);req.subscribe({next:()=>{this.cancel();this.load();},error:()=>this.error.set('Could not save the book.')});}
 remove(b:Book){if(confirm(`Delete “${b.title}”?`))this.api.books.delete(b.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Could not delete the book.')});}
}
